name: bhagavad_gita_flutter
description: A new Flutter project with Serverpod.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.5
  bottom_bar_matu: ^1.3.0
  google_fonts: ^4.0.4
  go_router: ^8.0.1

  in_app_update: ^4.0.1
  shared_preferences: ^2.1.2

  flutter_native_splash: ^2.3.0
  share_plus: ^6.3.4
  liquid_swipe: ^3.1.0


  flutter_local_notifications: ^14.1.1
  firebase_messaging: ^14.6.3
  firebase_crashlytics: ^3.3.3
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.3
  firebase_app_check: ^0.1.4+3


  carousel_animations: ^0.0.4
  video_player: ^2.2.19
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0

  flutter_easyloading: ^3.0.5
  stop_watch_timer: ^2.0.0
  fluttertoast: ^8.2.2

  
  url_launcher: ^6.1.11
  cached_network_image: ^3.2.3
  image_gallery_saver: ^2.0.2
  image_picker: ^0.8.8

  dio: ^5.2.1
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  flutter_rating_bar: ^4.0.1
  youtube_explode_dart: ^1.12.4
  pod_player: ^0.1.5
  path_provider: ^2.0.15
  gallery_saver: ^2.3.2


  hive: ^2.2.3
  on_audio_query: ^2.9.0
  hive_flutter: ^1.1.0
  get_it: ^7.6.0
  audio_service: ^0.18.10
  flip_card: ^0.7.0
  material_design_icons_flutter: ^7.0.7296


  sliding_up_panel: ^2.0.0+1
  html_unescape: ^2.0.0
  dart_des: ^1.0.2
  flutter_lyric: ^2.0.4+6
  audiotagger: ^2.2.1
  app_links: ^3.4.3
  palette_generator: ^0.3.3+2
  marquee: ^2.2.3
  metadata_god: ^0.4.1


  permission_handler: ^10.3.0
  flutter_displaymode: ^0.6.0
  connectivity_plus: ^4.0.1
  just_audio: ^0.9.34
  rxdart: ^0.27.7
  receive_sharing_intent: ^1.4.5
  file_picker: ^5.2.10
  carousel_slider: ^4.2.1
  http: ^0.13.6
  audio_session: ^0.1.16

  flutter_tts: ^3.7.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/flute2.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0
  riverpod_generator: ^2.2.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
