name: bhagavad_gita_flutter
description: A new Flutter project with Serverpod.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  bottom_bar_matu: ^1.3.0
  google_fonts: ^4.0.4
  flutter_local_notifications: ^14.1.0
  go_router: ^8.0.1
  in_app_update: ^4.0.1
  shared_preferences: ^2.1.2
  flutter_native_splash: ^2.3.0
  firebase_messaging: ^14.6.2
  share_plus: ^6.3.4
  liquid_swipe: ^3.1.0
  firebase_crashlytics: ^3.3.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  carousel_animations: ^0.0.4
  video_player: ^2.2.19
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0
  flutter_easyloading: ^3.0.5
  stop_watch_timer: ^2.0.0
  flutter_riverpod: ^2.3.6
  fluttertoast: ^8.2.2
  firebase_app_check: ^0.1.4+2
  url_launcher: ^6.1.11
  cached_network_image: ^3.2.3
  image_gallery_saver: ^2.0.1
  dio: ^5.2.1
  riverpod_annotation: ^2.1.1
  image_picker: ^0.8.8

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/qwise.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0
  riverpod_generator: ^2.2.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
