// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkzoeXUPI4ZAJz48rkC1HRbahymwBSnbw',
    appId: '1:724764116121:web:6f5a9c9bb371352c2de408',
    messagingSenderId: '724764116121',
    projectId: 'bhagavad-gita-ai',
    authDomain: 'bhagavad-gita-ai.firebaseapp.com',
    storageBucket: 'bhagavad-gita-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfD7vQgw8uqH29BsqH29ZJNvk029gYGaY',
    appId: '1:724764116121:android:b10f9de4c1fcb35e2de408',
    messagingSenderId: '724764116121',
    projectId: 'bhagavad-gita-ai',
    storageBucket: 'bhagavad-gita-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_00mY0wNKViSvki8LA5OsXqpwWD4sKW8',
    appId: '1:724764116121:ios:c1b68450271661972de408',
    messagingSenderId: '724764116121',
    projectId: 'bhagavad-gita-ai',
    storageBucket: 'bhagavad-gita-ai.appspot.com',
    iosClientId: '724764116121-v0lhib0h4v43n5drl47inon016789fgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhagavadGitaFlutter',
  );
}
