// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB56-b6UN0eE79ocFTC0B1ZUTxg1vjRQoo',
    appId: '1:43979308495:web:6ef13ebbdc6aa0149e26ba',
    messagingSenderId: '43979308495',
    projectId: 'bhagwavad-ai-gita',
    authDomain: 'bhagwavad-ai-gita.firebaseapp.com',
    storageBucket: 'bhagwavad-ai-gita.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbEoAcTNC1x6XyYA_fCkpxwkUggKxzQts',
    appId: '1:43979308495:android:1cef3d62893a999b9e26ba',
    messagingSenderId: '43979308495',
    projectId: 'bhagwavad-ai-gita',
    storageBucket: 'bhagwavad-ai-gita.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjqAP9mjMWLDJJ_Ll77QEzEfKnhu0Q4OE',
    appId: '1:43979308495:ios:780428c33801d50b9e26ba',
    messagingSenderId: '43979308495',
    projectId: 'bhagwavad-ai-gita',
    storageBucket: 'bhagwavad-ai-gita.appspot.com',
    iosClientId: '43979308495-v84v7grb1o76re2p6nrk40pirovod0c4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhagavadGitaFlutter',
  );
}
